version: '3.8'
services:
  postgres:
    image: postgres:13.5
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  prometheus:
    image: prom/prometheus
    volumes:
      - ${PWD}/prometheus:/prometheus-data
    command: --config.file=/prometheus-data/prometheus.yml
    ports:
      - 9090:9090
volumes:
  postgres:


