version: '3.8'
services:
  postgres:
    image: postgres:13.5
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  prometheus:
    image: prom/prometheus
    volumes:
      - ${PWD}/prometheus:/prometheus-data
    command: --config.file=/prometheus-data/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    # environment:
      # - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
volumes:
  postgres: 
  grafana-storage:


